"""xray 领域包：xray 二进制 + systemd 管理。"""

from xray.atom import (
    # 命令模板
    INSTALL_COMMAND,
    UNINSTALL_COMMAND,
    INSTALL_TIMEOUT,
    # 默认 config 相关
    DEFAULT_CONFIG_PATH,
    DEFAULT_PORT,
    DEFAULT_CONFIG_JSON,
    # 错误类
    XrayError,
    InstallFailedError,
    UninstallFailedError,
    VerifyFailedError,
    ServiceNotActiveError,
    EnableFailedError,
    StopFailedError,
    DisableFailedError,
    # 错误文案
    XRAY_INSTALL_FAILED_MESSAGE,
    XRAY_UNINSTALL_FAILED_MESSAGE,
    XRAY_VERIFY_FAILED_MESSAGE,
    XRAY_SERVICE_START_FAILED_MESSAGE,
    XRAY_SERVICE_NOT_ACTIVE_MESSAGE,
    XRAY_ENABLE_FAILED_MESSAGE,
    XRAY_SERVICE_STOP_FAILED_MESSAGE,
    XRAY_DISABLE_FAILED_MESSAGE,
    # 原子函数：通用软件管理契约（业务通常走 Manager，留着方便单测）
    install,
    uninstall,
    start,
    stop,
    enable,
    disable,
    is_installed,
    is_running,
    is_enabled,
    version,
    # 原子函数：xray 配置相关（暂留这里，下一轮搬到 xray/config.py）
    get_config_size,
    is_config_blank,
    write_default_config,
    test_internal_socks,
)
from xray.manager import XrayManager


__all__ = [
    "XrayManager",
    "XrayError",
    "InstallFailedError",
    "UninstallFailedError",
    "VerifyFailedError",
    "ServiceNotActiveError",
    "EnableFailedError",
    "StopFailedError",
    "DisableFailedError",
    "INSTALL_COMMAND",
    "UNINSTALL_COMMAND",
    "INSTALL_TIMEOUT",
    "DEFAULT_CONFIG_PATH",
    "DEFAULT_PORT",
    "DEFAULT_CONFIG_JSON",
    "XRAY_INSTALL_FAILED_MESSAGE",
    "XRAY_UNINSTALL_FAILED_MESSAGE",
    "XRAY_VERIFY_FAILED_MESSAGE",
    "XRAY_SERVICE_START_FAILED_MESSAGE",
    "XRAY_SERVICE_NOT_ACTIVE_MESSAGE",
    "XRAY_ENABLE_FAILED_MESSAGE",
    "XRAY_SERVICE_STOP_FAILED_MESSAGE",
    "XRAY_DISABLE_FAILED_MESSAGE",
    "install",
    "uninstall",
    "start",
    "stop",
    "enable",
    "disable",
    "is_installed",
    "is_running",
    "is_enabled",
    "version",
    "get_config_size",
    "is_config_blank",
    "write_default_config",
    "test_internal_socks",
]
